name: .NET

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore
      working-directory: ./src/Penca53.Variant/
    - name: Build
      run: dotnet build --no-restore
      working-directory: ./src/Penca53.Variant/
    - name: Publish  
      uses: brandedoutcast/publish-nuget@v2.5.5  
      with:   
        PROJECT_FILE_PATH: src/Penca53.Variant/Penca53.Variant.csproj  
        NUGET_KEY: ${{secrets.NUGET_API_KEY}} 
